### ISSUE TITLE
arco init my-project 报错

### ISSUE THREAD

**Issue by bqzhaoyan** [arco-design/arco-design-pro-vue#196]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.13
- **Browser:** chrome86.0.4240.198

## What is expected?
Error: Failed to copy project content.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

    at module.exports (C:\Users\ctvit\.arco_template_cache\1667352633921\node_modules\arco-design-pro-vue\.arco-cli\init.js:25:13)
    at C:\Users\ctvit\AppData\Roaming\npm\node_modules\arco-cli\node_modules\arco-cli-create-project\lib\index.js:129:23    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\ctvit\AppData\Roaming\npm\node_modules\arco-cli\node_modules\arco-cli-create-project\lib\index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: EBUSY: resource busy or locked, rmdir 'C:\Users\ctvit\.arco_template_cache\1667352633921\node_modules\arco-design-pro-vue'
node:fs:1180
  return handleErrorFromBinding(ctx);
         ^

Error: EBUSY: resource busy or locked, rmdir 'C:\Users\ctvit\.arco_template_cache\1667352633921\node_modules\arco-design-pro-vue'
    at Object.rmdirSync (node:fs:1180:10)
    at rmdirSync (C:\Users\ctvit\AppData\Roaming\npm\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:264:13)
    at rimrafSync (C:\Users\ctvit\AppData\Roaming\npm\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:243:7)
    at C:\Users\ctvit\AppData\Roaming\npm\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:279:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\ctvit\AppData\Roaming\npm\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:279:26)
    at rmdirSync (C:\Users\ctvit\AppData\Roaming\npm\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:269:7)
    at rimrafSync (C:\Users\ctvit\AppData\Roaming\npm\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:243:7)
    at C:\Users\ctvit\AppData\Roaming\npm\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:279:39
    at Array.forEach (<anonymous>) {
  errno: -4082,
  syscall: 'rmdir',
  code: 'EBUSY',
  path: 'C:\\Users\\ctvit\\.arco_template_cache\\1667352633921\\node_modules\\arco-design-pro-vue'
}

## Steps to reproduce
模版内容拷贝失败

**Comment by sHow8e** [comment]
@bqzhaoyan 保证是干净目录，同时目录不要使用中文。
