### ISSUE TITLE
npm install 失败

### ISSUE THREAD

**Issue by Sally-ws** [arco-design/arco-design-pro-vue#285]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.7.1
- **Browser:** chrome111.0.0.0

## Steps to reproduce
使用arco init创建项目，自动npm install失败，手动之后一直失败，以下错误是报的次数最频繁的，期间看了别人的方法配置过host，并不起作用
npm ERR! code 1
npm ERR! path E:\news\agent-pro\node_modules\gifsicle
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node lib/install.js
npm ERR! ‼ connect ETIMEDOUT 185.199.108.133:443
npm ERR!   ‼ gifsicle pre-build test failed
npm ERR!   i compiling from source
npm ERR!   × Error: Command failed: C:\Windows\system32\cmd.exe /s /c "autoreconf -ivf"
npm ERR! 'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
npm ERR! ���������ļ���
npm ERR!
npm ERR!
npm ERR!     at E:\chinacn\agent\agent-pro\node_modules\bin-build\node_modules\execa\index.js:231:11
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async Promise.all (index 0)

npm ERR! A complete log of this run can be found in: C:\Users\gyu\AppData\Local\npm-cache\_logs\2023-04-06T01_32_21_861Z-debug-0.log

**Comment by sHow8e** [comment]
@Sally-ws 手动安装也有问题么？

**Comment by sicraf** [comment]
npm安装不行，pnpm安装成功

**Comment by fengmikaelson** [comment]
$ node -v
v20.1.0
$ npm -v
9.6.4
不管windows还是linux都没成功过。。。

✔ Get project template successfully
✔ Template content copy completed
✔ Template content adaptation completed
✖ Project dependency installation failed, you can try to manually install them later
Error: Command 「npm install」 executed failed:
npm WARN ERESOLVE overriding peer dependency
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN deprecated trim@0.0.1: Use String.prototype.trim() instead
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code 1
npm ERR! path /data/vue/hello-arco-pro/node_modules/gifsicle
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! ⚠ 
npm ERR!   ⚠ gifsicle pre-build test failed
npm ERR!   ℹ compiling from source
npm ERR!   ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
npm ERR! autoreconf: Entering directory `.'
npm ERR! autoreconf: configure.ac: not using Gettext
npm ERR! autoreconf: running: aclocal  --output=aclocal.m4t
npm ERR! Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
npm ERR! autoreconf: failed to run aclocal: No such file or directory
npm ERR! 
npm ERR! 
npm ERR!     at /data/vue/hello-arco-pro/node_modules/bin-build/node_modules/execa/index.js:231:11
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async Promise.all (index 0)

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-05-06T05_53_44_546Z-debug-0.log

 arco-init  Project init failed! 
Error: spawnSync pnpm ENOENT

**Comment by sHow8e** [comment]
@fengmikaelson @sicraf @samchenws 换yarn 或者 pnpm 试试。

**Comment by cityiron** [comment]
i have the same problem

**Comment by burning110-lab** [comment]
我也有相同的问题
