### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by xiaosatufu** [arco-design/arco-design-pro-vue#8]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.0.2
- **浏览器版本:** chrome97.0.4692.71
- **复现地址:** https://github.com/arco-design/arco-design-pro-vue

## 额外补充
不知道为什么报错

## 预期结果
yarn run v1.22.17
warning package.json: "dependencies" has dependency "@arco-design/web-vue" with range "^2.13.0" that collides with a dependency in "devDependencies" of the same name with version "^2.0.0-beta.7"
$ vite --config ./config/vite.config.dev.ts
Pre-bundling dependencies:
  vue
  @arco-design/web-vue
  @arco-design/web-vue/es/icon
  echarts/core
  vue-router
  (...and 13 more)
(this will be run only when your dependencies or config have changed)

  vite v2.7.12 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 11873ms.

10:46:11 [vite] Internal server error:
G:\desktop\workspace\halfCooked\my-project\src\router\index.ts
  6:1  error  `@/layout/page-layout.vue` import should occur before import of `./modules/login`  import/order

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

  Plugin: vite:eslint
  File: G:/desktop/workspace/halfCooked/my-project/src/router/index.ts
      at formatError (G:\desktop\workspace\halfCooked\my-project\node_modules\vite\dist\node\chunks\dep-0351185a.js:36769:46)
      at TransformContext.error (G:\desktop\workspace\halfCooked\my-project\node_modules\vite\dist\node\chunks\dep-0351185a.js:36765:19)
      at TransformContext.transform (G:\desktop\workspace\halfCooked\my-project\node_modules\vite-plugin-eslint\dist\index.js:87:14)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Object.transform (G:\desktop\workspace\halfCooked\my-project\node_modules\vite\dist\node\chunks\dep-0351185a.js:36985:30)
      at async doTransform (G:\desktop\workspace\halfCooked\my-project\node_modules\vite\dist\node\chunks\dep-0351185a.js:52057:29)
10:46:11 [vite] Internal server error:
G:\desktop\workspace\halfCooked\my-project\src\store\index.ts
  16:1  error  `@/utils/env` import should occur before import of `./interface`  import/order

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

  Plugin: vite:eslint
  File: G:/desktop/workspace/halfCooked/my-project/src/store/index.ts
      at formatError (G:\desktop\workspace\halfCooked\my-project\node_modules\vite\dist\node\chunks\dep-0351185a.js:36769:46)
      at TransformContext.error (G:\desktop\workspace\halfCooked\my-project\node_modules\vite\dist\node\chunks\dep-0351185a.js:36765:19)
      at TransformContext.transform (G:\desktop\workspace\halfCooked\my-project\node_modules\vite-plugin-eslint\dist\index.js:87:14)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Object.transform (G:\desktop\workspace\halfCooked\my-project\node_modules\vite\dist\node\chunks\dep-0351185a.js:36985:30)
      at async doTransform (G:\desktop\workspace\halfCooked\my-project\node_modules\vite\dist\node\chunks\dep-0351185a.js:52057:29)

## 复现步骤
yarn dev

**Comment by xiaosatufu** [comment]
通过官网指引，安装完成启动后直接无法启动项目

**Comment by sHow8e** [comment]
@xiaosatufu 这个是eslint的报错哈。eslint有些包的版本更新后，行为会不一样，后续我们这边会兼容处理一下。你只要按照提示 “@/layout/page-layout.vue import should occur before import of ./modules/login import/order” 这个顺序调整一下就行了。

**Comment by xiaosatufu** [comment]
然而事实是，越改越多的eslint报错。。调整了顺序会出来更多的报错。不可能全部都要去调整吧 。。

**Comment by sHow8e** [comment]
> 然而事实是，越改越多的eslint报错。。调整了顺序会出来更多的报错。不可能全部都要去调整吧 。。

你可以把报错的规则在.eslintrc.js禁用掉。就不需要一个一个修改了。

**Comment by sHow8e** [comment]
新版本应该不会有初始化报错了。[https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.1.0](https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.1.0)

**Comment by cuijiudai** [comment]
运行：`arco init my-project ` 直接报错：

Error: socket hang up

**Comment by sHow8e** [comment]
@cuijiudai hi 这个是cli的报错。可以到 [arco-cli issue](https://github.com/arco-design/arco-cli/issues) 提供一下完整信息帮你排查问题哈。谢谢~

**Comment by cuijiudai** [comment]
> 

找到问题了，是我终端走代理了

**Comment by cuijiudai** [comment]
> @cuijiudai hi 这个是cli的报错。可以到 [arco-cli issue](https://github.com/arco-design/arco-cli/issues) 提供一下完整信息帮你排查问题哈。谢谢~

找到问题了，是我终端走代理了
